version: '3'

networks:
  nginx-php74-mariadb-node:

services:
  nginx:
    container_name: nginx_latest
    build: ./infrastructure/nginx/
    ports:
    # -"browser PORT":"nginx.conf container port"
      - "8080:80"
    links:
      - php
    volumes:
      - ./app:/usr/share/nginx/html
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-php74-mariadb-node
  php:
    container_name: php7.4
    build: ./infrastructure/php/
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    # seems like fpm receives the full path from nginx 
    # and tries to find the files in this dock, so it must
    # be the same as nginx.root
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - nginx-php74-mariadb-node  
  mariadb:
    container_name: mariadb10.4
    build: ./infrastructure/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: doc-comp_rootpass
      MYSQL_DATABASE: doc-comp_database
      MYSQL_USER: doc-comp_user
      MYSQL_PASSWORD: doc-comp_pass
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
    # -"browser PORT":"container port"
      - "4306:3306"
    networks:
      - nginx-php74-mariadb-node  
  node:
    container_name: node
    build: ./infrastructure/node
    #command: bash -c "npm install"
    volumes:
      - ./app:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    entrypoint: ['npm','install']
    networks:
      - nginx-php74-mariadb-node  